# Generated by Django 4.1.5 on 2024-11-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_food_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soup',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
