# Generated by Django 4.1.5 on 2024-11-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_branch_res_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='res',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.branch'),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('drink_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('soup_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='restaurant.branch')),
            ],
        ),
    ]
